/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TampilanRouteImport } from './routes/tampilan'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmbilRouteImport } from './routes/ambil'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiketIdRouteImport } from './routes/tiket.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TampilanRoute = TampilanRouteImport.update({
  id: '/tampilan',
  path: '/tampilan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbilRoute = AmbilRouteImport.update({
  id: '/ambil',
  path: '/ambil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiketIdRoute = TiketIdRouteImport.update({
  id: '/tiket/$id',
  path: '/tiket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambil': typeof AmbilRoute
  '/auth': typeof AuthRoute
  '/tampilan': typeof TampilanRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tiket/$id': typeof TiketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambil': typeof AmbilRoute
  '/auth': typeof AuthRoute
  '/tampilan': typeof TampilanRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tiket/$id': typeof TiketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ambil': typeof AmbilRoute
  '/auth': typeof AuthRoute
  '/tampilan': typeof TampilanRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/tiket/$id': typeof TiketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ambil' | '/auth' | '/tampilan' | '/admin' | '/tiket/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ambil' | '/auth' | '/tampilan' | '/admin' | '/tiket/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ambil'
    | '/auth'
    | '/tampilan'
    | '/_authenticated/admin'
    | '/tiket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AmbilRoute: typeof AmbilRoute
  AuthRoute: typeof AuthRoute
  TampilanRoute: typeof TampilanRoute
  TiketIdRoute: typeof TiketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tampilan': {
      id: '/tampilan'
      path: '/tampilan'
      fullPath: '/tampilan'
      preLoaderRoute: typeof TampilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambil': {
      id: '/ambil'
      path: '/ambil'
      fullPath: '/ambil'
      preLoaderRoute: typeof AmbilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiket/$id': {
      id: '/tiket/$id'
      path: '/tiket/$id'
      fullPath: '/tiket/$id'
      preLoaderRoute: typeof TiketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AmbilRoute: AmbilRoute,
  AuthRoute: AuthRoute,
  TampilanRoute: TampilanRoute,
  TiketIdRoute: TiketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
